#!/usr/bin/env bash
# This scripts displays:
# - The content of the current directory
# - In a list format where only the part
# - of the name after the first dash is displayed

for f in *; do
    echo "$f" | cut -d '-' -f 2

done
